import { GameInfoComponent } from './game-info/game-info.component';
import { ImageDialogComponent } from './image-dialog/image-dialog.component';
import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';

declare const L;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'justplay-shic';

  mymap;

  times = [];

  annuario = [];

  constructor(
    private dialog: MatDialog
  ) {
    
  }

  ngOnInit() {
    this.mymap = L.map('map').setView([51.50900640598445, -0.11960303487590755], 14.5);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
      maxZoom: 18,
      id: 'mapbox/streets-v11',
      tileSize: 512,
      zoomOffset: -1,
      accessToken: 'your.mapbox.access.token'
    }).addTo(this.mymap);
    const imageUrl = '/assets/ddt/map/{z}/{x}/{y}.png';

    L.tileLayer(imageUrl, {
      minZoom: 12,
      maxZoom: 17,
      tms: false,
      attribution: 'Generated by TilesXYZ'
    }).addTo(this.mymap);


    for (let i = 1; i < 22; i++) {
      this.annuario.push({ url: '/assets/ddt/annuario/Annuario-page-' + i.toString().padStart(3, '0') + '.jpg' })
    }
    for (let i = 1; i < 21; i++) {
      this.times.push({ url: '/assets/ddt/times/Times-page-' + i.toString().padStart(3, '0') + '.jpg' })
    }


  }

  show(title, url, width)  { 
    this.dialog.open(ImageDialogComponent, {data: {title, url, width}});
  }

  gameInfo() {
    this.dialog.open(GameInfoComponent);
  }

}
